
spring.application.name=chat-app-backend

# spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/chatapp}
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=chatapp

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

groq.api.key=${GROQ_API_KEY}